version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: order_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rohit11
      POSTGRES_DB: online_shopping_order_service_db
    ports:
      - "5434:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data

volumes:
  order_postgres_data: