version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: inventory_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rohit11
      POSTGRES_DB: online_shopping_inventory_service_db
    ports:
      - "5435:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

volumes:
  inventory_postgres_data: